Update HTTP headers for compatibility with Chrome version 100 and later
The default Content Security Policy of Chrome has been changed to
prohibit WASM code execution and leads to the following error message:

CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder

Update the "script-src" flags of the Content Security Policy header to
allow WASM execution again.